### ISSUE TITLE
(Bug) (Android) won't save

### ISSUE THREAD

**Issue by agergo100** [Wohlstand/TheXTech#111]
I don't know this is a bug or not but some reason the game not store any saves.
After left the episode with "Save and quit" and check the saves, nothing even the save won't save the game.

**Comment by Wohlstand** [comment]
Do you mean you can't resume the game after "Save and quit", or you just won't find game saves? For the case of game saves, they all get saved not in the episode directory itself: they all get to appear at `settings/gamesave/<episode directory name>/<worldmap-name>-save-x.savx`. That was done to make episode directories being not trashed by any junk files and keep episode directories being read-only file system friendly.

**Comment by agergo100** [comment]
I finally realised why won't creates save.
The smbx folder is in the sdcard had placed and that the reason of the missing saves.

**Comment by Wohlstand** [comment]
That weird that the game won't write saves here... Does it save settings like custom keyboard/joystick controls?

Also, which Android version and device model you do have?

**Comment by agergo100** [comment]
Android 9

**Comment by Wohlstand** [comment]
Okay, I guess, I need to check out this thing:
https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android
I had to just miss up something... A bit later I'll try to make some and I'll let you know, then you can try the devel build after

**Comment by Wohlstand** [comment]
I'll try to investigate this on Friday, now I release the 1.3.5.1 and I'll note this bug as known.

**Comment by Wohlstand** [comment]
Okay, I tried in the emulator to put game resources on the SD card, and yes, it won't write anything into it, but it reads the stuff fine. Gonna try some workarounds on game saves storage per assets and the way to store game settings too. They will also don't be saved. Probably I'll just save all game settings at the in-app directory rather than saving that stuff at the assets directory here. This will add the limitation that you can't easily transfer game saves without copying files from the `Android/data/ru.wohlsoft.thextech/...` directory. However, I'll try to use this way as a fallback for read-only assets storages like SD cards here. Looking around I see it's tricky to allow the SD card writing directly here.

**Comment by Wohlstand** [comment]
Hello!
I finally fixed this bug, so, please take the latest build from here:
<https://github.com/Wohlstand/TheXTech/wiki/Fresh-devel-builds>
and tell me, did this bug gone or not?

So, what I did:
- I added the write ability test for the assets path
- If the selected assets path is not writable for any reason, I do use the application data directory (`/data/data/ru.wohlsoft.thextech/files/<assets directory name>/`) to save settings, logs, in-game screenshots, and GIFs, etc. So, it's just a workaround to just allow you save the game and it's settings.

**Comment by Wohlstand** [comment]
Okay, I'll close this as the problem has been solved, but I'll keep the NEED A TEST tag until @agergo100 will test the thing and confirm the bugfix.

**Comment by agergo100** [comment]
Now can save.

**Comment by Wohlstand** [comment]
Thank you for confirmation, gonna remove the tag.
