### ISSUE TITLE
[Discussion] How creator's non-SMBX 1.3 custom assets will be named without conflict for future developments

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#115]
In future, TheXTech may allow for new background, background2, block, effect, level, npc, path, scene, and tiles. Users like me and Love Bodhi have desired more BGOs and world map sceneries per-level or etc. How will we allow the player to name these so that they can be recognized by TheXTech without download of config pack, or Wohlstand adds objects with IDs that the player already used?

My suggestion: player's customs are named such as "block-custom-1.png" or "block-1-custom.png". TheXTech will read these per-level without require a config pack or download, and Wohlstand's new hardcoded object additions will never conflict with these names. I think max array of each of these should be generous such as 1000 for the current time.

**Comment by ds-sloth** [comment]
I agree that allocating a unique namespace to custom assets is a good idea. To avoid clutter, maybe they can be "block-c1.png" instead of "block-custom-1.png"?

| I think max array of each of these should be generous such as 1000 for the current time.
We should also work to be careful with how much RAM these require. On low-RAM targets, a number of expanded maximums (especially `maxSections`) need to be returned to their original values to avoid stack-overflows. Perhaps the maximum number of new custom assets could follow the same `LOW_MEM` compile-time flag I have introduced.

**Comment by Wohlstand** [comment]
If that a discussion, then I'll make it as discussion :wink: :fox_face:
