### ISSUE TITLE
Feature Request: Dragon Coins on HUD

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#122]
There's no way to know how many Dragon Coins you've collected in a stage other than remembering them. It would be nice if they displayed on the HUD somewhere like in Super Mario World, the graphic used in SMW is already present on the HUD for the coin counter.

**Comment by Wohlstand** [comment]
Good idea, at least, make that work in next conditions:
- the compat.ini option enables it
- all necessary resources were presented
- add an option that will make them don't appear again after collection
Also, I MUST to make dragon coins to NOT transform on a P-Switch

**Comment by Wohlstand** [comment]
It's needs to be made carefully as dragon coins use can be abused in some cases.

**Comment by ChristianSilvermoon** [comment]
The only reason I can imagine for not making them appear on the HUD in certain episodes is that it might break immersion slightly if they've been re-sprited, but realistically it shouldn't impact gameplay itself at all if added :thinking:

**Comment by LoveBodhi** [comment]
Remind me "Star Coins"!

**Comment by P-Star7** [comment]
HUD asset exists already (SMW coin logo), but users may want a different graphic, and also maybe "uncollected" logo to count all the remaining coins. I wonder if this option should be expanded to other NPC's deaths, since Dragon Coin's death function is what will be read for the HUD change anyways.

**Comment by ChristianSilvermoon** [comment]
> HUD asset exists already (SMW coin logo), but users may want a different graphic, and also maybe "uncollected" logo to count all the remaining coins. I wonder if this option should be expanded to other NPC's deaths, since Dragon Coin's death function is what will be read for the HUD change anyways.

If going that direction, I think it'd be better to support adding/manipulating HUD elements through events rather than making it a part of Dragon Coin tracking, which be just showing info on screen that the game already tracks.

**Comment by ds-sloth** [comment]
Has been implemented using the score counter for dragon coins. Maximum of 8 (5 UP) shown on screen (at which point they award 5 UP).

I think that we should certainly use the SMW coin logo because (1) that is how SMW does it, and except in rare cases this game is inspired by the innovations of that series; (2) assets are already designed to make SMW coin logo visible against all background (since it is used for coins); and (3) that minimizes the number of assets that must be loaded at one time.

Question: what should the positioning be? Ideally, the coin and life counters should have the same height, and ideally the HUD would not expand too much. This is the best I can think of right now, but there may be other better approaches.

![Scr_2021-07-07_17-40-03](https://user-images.githubusercontent.com/72112344/124832375-98db1280-df4a-11eb-9998-53c116bddd0c.gif)

**Comment by 0lhi** [comment]
Awesome :D

I think the best position would be where SMBX2 displays it's Star Coins:

https://i.imgur.com/fSoV4nO.png

There should be an option to load a dedicated Yoshi Coin graphic (dragoncoin-hud.png). When there is none, it should fallback to the SMW Coin, which can be the default case.

Questions:

Is it possible to enable a Coin Counter, like the Star Coins in SMBX2? The number could be set via Compat.ini.

Is it possible to have it track individual coins? For example by adding an event to each coin that is entered in Compat.ini?

It is possible to save collected Coins and make them half-transparent on future visits? 


```ini
[Dragoncoins]

show-dragon-coins = true
coin-number = 3
coin1 = Event 1
coin2 = Event 2
coin3 = Event 3
save-collected-coins = true
```

**Comment by ChristianSilvermoon** [comment]
Displaying more than 5 on the HUD looks strange, but seems perfect to me :P

**Comment by ds-sloth** [comment]
So, the benefit of what I have here is that it is easy for both us (as developers) and the episode creators.

@0lhi, your suggestion seems to be basically making a full-blown star coin system, which I'm not opposed to, but is definitely a lot more work.

I do believe, however, that it can be automated so that the episode creators do not need to provide that much information. The main challenge would be to produce a heuristic for the order of the dragon coins appearing in the level, but the benefit is that even legacy episodes could track dragon coins. (Of course, using events would make it extremely flexible for episode creators.)

**Comment by 0lhi** [comment]
> @0lhi, your suggestion seems to be basically making a full-blown star coin system

Pretty much ^-^> There are some SMBX2 episodes that don't use many features beyond the SMBX64 standard, but one that is frequently used are Star Coins. "The Epic Quest" was even ported to X2 specifically because of them. I think that giving TheXTech a similar system would benefit it greatly.

> I do believe, however, that it can be automated so that the episode creators do not need to provide that much information. ...the benefit is that even legacy episodes could track dragon coins. 

:o That would be amazing!

In that case, a compat.ini for rearranging the tracking orders of sections could be beneficial, as their numbers do not necessary match the order the player visits them in.

**Comment by Wohlstand** [comment]
You can utilize the `Special*` fields to make options (then, but the "special value" from NPC at PGE-X into them), and then, at the config pack for Moondust Devkit to make it have the special value being enabled, I guess, soon I gonna upload my TheXTech SDK config pack, but it's a bit unfinished, mainly because of a minor set of important updates I want to apply at the Editor itself:
- Apply all config pack settings into Editor settings, don't override the `main.ini` which is done currently by all integrational config packs, that sucks
- Fix the splash logo broken at the rest of international config packs

**Comment by ds-sloth** [comment]
> In that case, a compat.ini for rearranging the tracking orders of sections could be beneficial, as their numbers do not necessary match the order the player visits them in.

I was going to use a pathfinding algorithm using the entrances and exits of the sections.

If we don't do it automatically, how does the SMBX2 format do this? We could try something similar.

**Comment by 0lhi** [comment]
> If we don't do it automatically, how does the SMBX2 format do this? We could try something similar.


https://user-images.githubusercontent.com/74732674/124976193-3c055800-e02f-11eb-81b4-09851f692f21.mp4

**Comment by Wohlstand** [comment]
> If we don't do it automatically, how does the SMBX2 format do this? We could try something similar.

You can:
- in the game, use the `.Special*` fields, and bypass one from PGE-FL the "special_value" field
- extend the PGE-FL to add into SAVX format fields that can save data needed for per-level dragon/star coins reminded
- when getting such of dragon/star coins, save them into the list, and the list write into SAVX file by PGE-FL

**Comment by 0lhi** [comment]
I think, the SMBX2 approach is the way to go. It is intuitive, already familiar with level designers, and likely easier to implement than an automatic approach.

It would also avoid the need to make a compat.ini feature, since only new episodes would have special values.

Also, I think that vanilla levels with undefined amounts & positions should display the coins like "o x 7" instead of "ooooooo". That avoids the limitation.

**Comment by ds-sloth** [comment]
I have enough teaching and school coming up in the next two months that I don't think it's a good idea for me to write a full path-finding algorithm. :) There are still a number of things much higher on my priority list than this particular enhancement.

Let's go ahead and take the SMBX2 approach with the extended level format. When the developer didn't specify an order, let's track them but allow them to be unordered (making this clear by not having any outlines for the coins).

@Wohlstand, would you be able to take the lead on this enhancement moving forward? You have a much stronger understanding of the current level formats code, and you would be able to implement the corresponding enhancements in your Moondust Editor.

**Comment by Wohlstand** [comment]
Yeah, I'll take some tweaking on my side, and that will need me add some into SAVX format to remember the state of them. Also, off topic, I want to allow more stars being registered per level, so, let every star get an id (set by user, or automatically assigned by order In a file), and save the star's ID at level instead of section where it was placed, making them tracked fairly.

**Comment by Wohlstand** [comment]
I'll check some after sleep...

**Comment by 0lhi** [comment]
Since it's on-topic in the Chatroom now, here's how it looks like in SMBX2:

https://i.imgur.com/MGDqUoM.mp4

**Comment by ChristianSilvermoon** [comment]
I believe this was implemented as of a94aa4d

**Comment by 0lhi** [comment]
> I believe this was implemented as of [a94aa4d](https://github.com/Wohlstand/TheXTech/commit/a94aa4d1d2ea291f7a5910b6c922803808001b3f)

There are still things to discuss (position, how to track them etc).

**Comment by ds-sloth** [comment]
Yes, this one is still somewhat uncertain. At the time we discussed this I implemented some very basic pathfinding code that attempts to order the collectibles, but it's not ready for prime time yet.

**Comment by ds-sloth** [comment]
@ChristianSilvermoon can this Issue be closed?

<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/cb2139f9-7fb1-4014-a991-4b9d4fcd4bb2" width="400" height="300">

**Comment by Wohlstand** [comment]
Closing!
