### ISSUE TITLE
Customized Coins cause problems with P-Switch

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#167]
**Describe the issue**

Custom Coin Sprites and npc-x.txt configs cause the Blocks to be placed weirdly, and after the P-Switch timer ends, the coins are no longer animated.

**Example Case**

[Coin Test.zip](https://github.com/Wohlstand/TheXTech/files/9570488/Coin.Test.zip)

**Recording**

![Scr_2021-08-20_13-27-40](https://user-images.githubusercontent.com/74732674/130231018-6cc1abe9-8a8c-402f-a2d0-476ad555bcc7.gif)

Here's the case with no customizations:

![Scr_2021-08-20_13-26-25](https://user-images.githubusercontent.com/74732674/130231300-1a096832-8687-4853-b832-6fcc62805bf5.gif)

**Vanilla Recording**

Tried to do a PNG to GIF conversion for Vanilla, but it didn't work:

![CoinVanilla](https://user-images.githubusercontent.com/74732674/130231375-6f3f3092-fc6f-40ec-b447-d9b462b1b0a0.png)

**Additional context**

The coins have a customized size, except npc-152 (Sonic Ring), which just has a different amount of frames.

**Comment by 0lhi** [comment]
Even placing only one of the modified Coins in the level folder will prevent it from working on Vanilla. Except for npc-152, whose size is unchanged. The animation will still freeze though.


https://user-images.githubusercontent.com/74732674/130287472-0f353f40-e6ce-44f9-9ba9-440637a91326.mp4

It appears that on Vanilla, the Bug is either game-breaking or purely visual. In both cases, no compatibility feature would be required.

**Comment by P-Star7** [comment]
This also applies even when customizing the coin in vanilla. The animation does not sync up as the player scrolls the coins on screen. I think the animation timers for each type of coin:
-SMB3 Yellow
-SMW Yellow
-SMB1
-SMB3 Red
-Sonic
-Rupee Green
-Rupee Blue
-Rupee Red
-SMW Blue
-SMW Dragon/Yoshi

all need to read their frame amount from the npc-x.txt. As we can see with coins vs. rupees, there are clearly multiple animation timers for coins. So this means that it's possible to have individual animation timers for the coins.

**Comment by ds-sloth** [comment]
This can be fixed by initializing the coins' frames correctly when they are created.

I tentatively agree that this is cosmetic and I'm not adding a compat flag for it just yet. I've looked briefly at the `NPCFrames` code for coins with custom frames, and the `EditorNPCFrame` function, and I don't think there is any random state changing or any side effects.

As for the mispositioned blocks, this is actually because the NPCs themselves were originally mispositioned.

<img src="https://user-images.githubusercontent.com/72112344/197361501-e13a9d7e-741a-47f3-b395-883f3c0caa3a.gif" width="400" height="300">

When saving the file again after fixing the NPC locations ([Coin Test-fixed.zip](https://github.com/Wohlstand/TheXTech/files/9845231/Coin.Test-fixed.zip)), the problem does not occur.

<img src="https://user-images.githubusercontent.com/72112344/197361666-b01051ad-71ec-48ea-b38e-b1728a64da25.gif" width="400" height="300">

We can't automatically correct the NPCs' positions because that (1) dramatically alters gameplay outcomes, and (2) creators may have intentionally positioned the NPCs off-grid.

**Comment by ds-sloth** [comment]
Additional information about the NPCs' original incorrect placement:

The game expects NPCs to be centered in their 32px columns, and the editor reliably does this, no matter what the size of the NPC is. But, if you open the level with a different set of NPC sizes than it was saved with, then the game will (and has always) position the NPC with the same left coordinate it had when saved, putting it off-center. NPCs are only correctly placed, by default, when their size hasn't changed after they were placed.

**Comment by ds-sloth** [comment]
Can you please verify (at your convenience) whether the updated build correctly restarts the coins' animation?

**Comment by LoveBodhi** [comment]
![Scr_2022-10-23_11-19-24](https://user-images.githubusercontent.com/37089530/197371718-8cf222d9-a6ed-47c8-88e7-e72765b1ddbe.gif)
I made a test in the Nostalgic Paradise asset.

**Comment by 0lhi** [comment]
Works!

![Scr_2022-10-25_20-10-26](https://user-images.githubusercontent.com/74732674/197850970-2de4e8ef-278f-44f2-b4ad-ddddd3260c43.gif)
![Scr_2022-10-25_20-17-52](https://user-images.githubusercontent.com/74732674/197850995-3f52f93f-d5d6-40ef-9924-ae0e515ec9a6.gif)
