### ISSUE TITLE
(Bug) (Vita) Custom assets won't load on downloaded episodes

### ISSUE THREAD

**Issue by solicsnace** [Wohlstand/TheXTech#170]
Not too sure whether its the episodes I've downloaded or the WIP port itself, but majority of the custom assets used in custom episodes have massive black borders around them. All of the episodes I've downloaded are from [here](https://www.supermariobrosx.org/forums/viewtopic.php?f=36&t=17194), I'll show some images as examples:

![unnamed](https://user-images.githubusercontent.com/89723311/131242179-549a1fa0-aa41-4565-8f45-3096f9f50d20.jpg)
 
From SMB: Revisited

![unnamed (1)](https://user-images.githubusercontent.com/89723311/131242209-2c056495-e1c2-46e7-a617-394c0b83d874.jpg)

From Return to Dinosaur Land

![unnamed (2)](https://user-images.githubusercontent.com/89723311/131242230-5adea2be-d580-4f3c-981c-5fbc43352624.jpg)

From Return to Yoshi's Island

**Comment by suicvne** [comment]
This is a known issue, this is related to this episode using the old GIF based mask graphics which don’t currently work on Vita. The black borders that you’re seeing are due to missing masks. 

The episodes with these issues should be converted with GIFs2PNG (link coming later) until GIF mask support is properly debugged and fallback masks are implemented.

**Comment by suicvne** [comment]
OK, custom graphics with masks should load now as of commit 67ed8e8ef0425e3da2f9db411e683cf526c3b222
In addition, there was a logic bug found in the graphics code that probably produced the strange background that you saw in the second screenshot. It should also fix weirdness that happens when playing the game for a long time.

The latest Vita build is available through CI, or at the link below:
https://github.com/suicvne/TheXTech/releases/tag/v1.3.6-vita-alpha

**Comment by Wohlstand** [comment]
@suicvne , is this issue actual? Or we can close it?

**Comment by suicvne** [comment]
@Wohlstand This can be closed. This is a remnant from some of the earliest versions of the port, before fixed to PGE_File_STL were in place.

**Comment by Wohlstand** [comment]
Lubrary called "PGE File Library", and the STL is the suffix that meant early goal to port PGE-FL into STL from Qt. But thanks for the confirmation that it's outdated now :)
