### ISSUE TITLE
(Config) Limit playable characters to their .wld-version's limitations

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#223]
This is an option in the config that would limit characters in episodes created before 1.2.2 to only the options that were available at the time.
SMBX 1.0-1.2.0 Beta 4 - Mario is enforced in single player, Mario is player 1 and Luigi is player 2 in multiplayer
SMBX 1.2.1 - The player can now select between Mario and Luigi in single player. However, it is still enforced in multiplayer that Mario is player 1 and Luigi is Player 2.
SMBX 1.2.2+ - The system works as in modern times. The .wld now has support for blocking certain players.

This request was added because, in episodes like The Princess Cliche, The Great Castle Adventure, or Return to Yoshi's Island, the creators made it with the intention that Princess Peach was not playable, and thus had to be rescued. In addition, some older levels may not be completable due to requiring Yoshi usage, spin jump, or the many things that Link cannot do (Kuribo's Shoe, hold items, etc.), and the creators had no way of knowing that playable characters. without Mario and Luigi's abilities could be used later.

I do not know if this config should be on or off by default. But it would still be fun to allow it to be turned off if the player wants, just to have fun in the old episodes.

**Comment by Wohlstand** [comment]
Btw, please use exact build numbers than game versions, that's because these build numbers were used to identify conditions:
https://github.com/Wohlstand/TheXTech/issues/185

Also, I had to set build 30 as a minimal build version that allows playing as any character, mainly because if using build 50 (the first version that introduces new players), breaks some episodes like The Invasion 2, because its world map was built with an older version....

**Comment by Wohlstand** [comment]
P.S. I guess, this is going to be a sub-task for #185

**Comment by 0lhi** [comment]
Closing. See #185.
