### ISSUE TITLE
Lighting/Transparency Issues

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#240]
**Describe the issue**

Several Episodes that make use of a Transparency Workaround end up looking inaccurate or ugly on TheXTech.

**Example Case**

W2-L1 Calamity Caves from [Reign of the Gatekeeper](https://www.supermariobrosx.org/forums/viewtopic.php?f=36&t=18547):

Recording: [TheXTech](https://clips.twitch.tv/SneakyRepleteGiraffeHassanChop-jIIIdp7r2VQ8fZ0L) • [Vanilla](https://clips.twitch.tv/FurtiveWisePuddingMrDestructoid-mecjGFlgO67fvx7X)

![Reign](https://user-images.githubusercontent.com/74732674/147886509-50f65f65-a26d-4e9c-8441-92e9cf558f5a.png)

Hub 1 Spirit Kingdom from [The Fallen Spirits](https://smbxarchive.wohlsoft.ru/SMBX%201.3/The%20Fallen%20Spirits.7z):

Recording: https://imgur.com/a/MWFa8b8

![FallenSpirits](https://user-images.githubusercontent.com/74732674/147886544-2548b236-f9a3-4c6e-be39-584bf654287d.png)

**Additional Context**

For Yoshi's Archipelago, [a workaround](https://wohlsoft.ru/forum/viewtopic.php?p=20248#p20248) was added in 2020 that makes the episode look okay, but it doesn't work as a universal solution.

![Archipelago](https://user-images.githubusercontent.com/74732674/147886678-637862f4-0a86-4dff-b204-fb077050118d.png)

**Comment by Wohlstand** [comment]
The problem that even I want to replicate masked render (Blending of mask using AND, and blending front using OR), SDL Render won't allow that.  Somewhere ago I made a request to provide the support for AND and OR blit algorithms, but was been rejected as "requires custom shaders" or something, lemme find original discussion....

**Comment by Wohlstand** [comment]
Found, it's this: https://github.com/libsdl-org/SDL/issues/2404
I posted it a while ago, SDL2 team had used Bugzilla at that time.
Anyway, I want to join the @slouken to ask, where bitwise AND/OR blending requires a custom shader?

What I actually know:
- at Windows' GDI there is exact AND and OR BitBlt modes, they were originally used at SMBX to render. Other software based renderers would have the similar case
- At OpenGL there is need to enable one small extension to allow bitwise blending, I sent an example link at that discussion

**Comment by Wohlstand** [comment]
And so, if I use OpenGL directly (that I do at Moondust Engine), then thing will work. But, when I use SDL Render as an universal overlay for software render, it doesn't allow me this.

**Comment by 0lhi** [comment]
> And so, if I use OpenGL directly (that I do at Moondust Engine), then thing will work. But, when I use SDL Render as an universal overlay for software render, it doesn't allow me this.

Interesting. The PCSX2 Emulator allows to flexibly switching around between Hardware and Software Mode by pressing the F9 Button for cases where the Hardware Render is inaccurate:

https://user-images.githubusercontent.com/74732674/147893171-b4decfea-eeff-4167-9752-fc896c6d6327.mp4

Do you think that approach could work for TheXTech/Moondust as well?

(Funfact: At my #143 Hotkey Feature Request, the F9 Spot is free.)

**Comment by Wohlstand** [comment]
As I explained, case would go opposite: software won't draw as needed, because OpenGL allows such tricks. By the way, modern shaders allows lots of black magic, so, can solve hardware problems of specific software

**Comment by Wohlstand** [comment]
Otherwise, to make software, I will need to manually blit the surface that will take a lot of energy

**Comment by 0lhi** [comment]
> As I explained, case would go opposite: software won't draw as needed, because OpenGL allows such tricks.

I understood that. I still think the approach would be beneficial even when the case is reversed.

There are 3 Groups of Users:

- Group 1 uses Hardware Mode (default)
- Group 2 prefers Software Mode for whatever reason
- Group 3 has to use Software Mode

Using OpenGL directly would fix the issue for the first Group. Allowing for an instant switch with F9 as a Hotkey would offer a quick workaround for Group 2. That has the majority of users covered without giving you a painful task.

Group 3 would be uncovered for the time being. Would be unfortunate, but okay, since there are not many Episodes that make use of this feature.

**Comment by 0lhi** [comment]
Yes, Software Mode isn't accurate, and won't be due to SDL limitations. So people who prefer Software Mode but can use Hardware Mode should get the possibility to change on the fly.

Furthermore, the ability to quickly change will make it tremendously easier to test graphics-related stuff in the future.

**Comment by ds-sloth** [comment]
Okay, Wohlstand or I can set this up with a hotkey after Wohlstand implements it.

**Comment by Wohlstand** [comment]
Hi there!

Today, I got some ideas, and I guess, by SDL Render API I could make some with fewer overloads, so, the next algorithm:
- take the x/y/w/h area where target texture can be rendered
- compute the bitwise AND sum of every pixel of mask and the taken surface fragment
- then, compute the bitwise OR sum of every pixel of front and the result of the previous operation
- draw the resulting surface back into the target texture.

Additionally, to avoid performance going down, I should make the next on-loading check:
- Mask has only black and white colors
- Mask doesn't matches with the front (aka, it's not a form of the "lazily-made" sprite)

So, use a mask once these conditions above aren't passed, otherwise, just convert into RGBA as usual.

**Comment by slouken** [comment]
Have you guys looked at SDL's custom blend modes? They won't be super fast
in software mode, but they might have the functionality you want
without custom shaders.

e.g.
SDL_BlendMode blend = SDL_ComposeCustomBlendMode(
SDL_BLENDFACTOR_ONE_MINUS_DST_COLOR,
SDL_BLENDFACTOR_ONE_MINUS_SRC_COLOR, SDL_BLENDOPERATION_ADD,
SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD );
SDL_SetRenderDrawBlendMode( renderer, blend );

**Comment by slouken** [comment]
Actually, custom blend modes aren't supported by the software renderer at
all anyway.

**Comment by 0lhi** [comment]
I think, we should prioritize making Hardware Mode accurate first and not touch the SDL Render for now.

Once Hardware Mode supports OpenGL directly and the Hotkey is added, we'll have a better Playground for SDL Experiments.

**Comment by Wohlstand** [comment]
> Have you guys looked at SDL's custom blend modes? 

@slouken, We needed the different blend operation: right now there are supported ADD and SUBTRACT, but we need bitwise AND and bitwise OR operations, i.e. `dst &= src` and `dst |= src`

**Comment by Wohlstand** [comment]
Just now I made the dirty experiment at the side branch (don't go to merge somewhere, just a sandbox branch), and there is a software method that draws the bitmask thing:
https://github.com/Wohlstand/TheXTech/blob/wip-bitmask-test/src/core/sdl/render_sdl.cpp#L580-L634

Result gets accurate, but, obviously, very slow if too many bitwise-drawn textures are shown on the screen:

![Scr_2022-01-09_12-30-20](https://user-images.githubusercontent.com/6751442/148676847-fbf06f14-42b0-46bb-a08e-ccb9913e60b0.png)

**Comment by P-Star7** [comment]
Has JzAzBz blending algorithm been written by anybody yet? Look at here, and you will find that it provides for better gradients than RGB blending. However, it is more computationally intensive (due to converting raw RGB data -> XYZ data -> JzAzBz data -> XYZ data -> RGB raw data to display as the pixels), so it definitely must be optional if it is ever added.
[](http://gramaz.io/chromaticity/)
The best colours to try with the gradient maker is with the main 8 RGB colours (white, yellow, cyan, green, magenta, red, blue, black). The gradient of white and blue shows a dramatic change, with JAB having a much more natural sky-blue tone compared to the RGB cornflower-like colour.

**Comment by 0lhi** [comment]
@ds-sloth I made the Minimal Case. It has 2 sections featuring lighting tricks from 3 episodes. Result must match this:

[Light.zip](https://github.com/Wohlstand/TheXTech/files/9330168/Light.zip)
![Section1](https://user-images.githubusercontent.com/74732674/184453926-1651648d-2044-413d-90c6-86bb85e86aa5.png)
![Section2](https://user-images.githubusercontent.com/74732674/184453934-49220e5a-70c1-451b-8725-6bf83bed85e0.png)

**Comment by ds-sloth** [comment]
Can I better understand what a solution to this would look like?

We now have lots of TheXTech assets that assume that transparency is blended the modern way, so we can't just switch the entire renderer to using this old formula. Would we want to switch blend mode per-texture? How would we indicate whether a texture would use the modern or the old way?

**Comment by 0lhi** [comment]
> We now have lots of TheXTech assets that assume that transparency is blended the modern way

Do we? Can you give some examples?

In my understanding, TheXTech assets usually use PNGs, no? While this old way is a result of unusual usage of Mask GIFs.

If people made Mask GIFs for TheXTech exclusive content, then I'd say: Don't do that.

Otherwise, I don't really get what you mean. SMBX64 can't do PNGs so we don't need to change anything for PNGs. @ds-sloth

**Comment by 0lhi** [comment]
Btw, with our [Project Goals](https://github.com/Wohlstand/TheXTech/wiki/Project-Goals) putting the preservation of SMBX64 Logic on top, the priority of this Bug needs to be reconsidered. @Wohlstand

**Comment by ds-sloth** [comment]
PNGs and GIF+grayscale mask GIFs encode precisely the same information, and I would like to be able to treat each of them in the same way. Otherwise, we’d need to have two classes of textures internally, and switch between blend modes on the fly, which is quite expensive.

Second, I don’t want GIFs to have any advantages over PNGs for content for TheXTech. If someone wants to make one of these effects for TheXTech, they shouldn’t be required to use GIFs.

The content I was referring to was PNG content that assumes that alpha blending is done the modern way.

**Comment by ds-sloth** [comment]
I wanted to add a quick update here about the status of this issue based on various conversations amongst the devs elsewhere:

- **Vita/OpenGL ES**: @suicvne is planning to implement an OpenGL ES 2.0 renderer for Vita which will probably become our main renderer for desktop, web, and mobile platforms (if it works well). This will support a programmable pipeline and we should be able to write pixel shaders to emulate this behavior.
- **OpenGL legacy**: I am planning to write a legacy OpenGL renderer (probably 1.1) for our very old desktop targets. All versions of legacy OpenGL natively support logic op rendering.
- **SDL2**: @Wohlstand already implemented a software version in a wip branch that we might be able to fall back on when neither of these options are available, but the performance is low when many logic op objects are onscreen at once. I don't know whether we'll want to use it by default or not.
- **Switch**: I'm not certain whether our Switch SDL2 port exposes any OpenGL ES functionality, but we'd likely be able to use the GLES renderer or a variant of it there.
- **Wii**: The Wii renderer natively supports logic op rendering.
- **3DS**: The 3DS renderer would require a new shader and I'm not familiar enough with the PICA 200 GPU's shader language to do this right now, but it's in theory possible.

**Comment by ds-sloth** [comment]
I added a small sandbox test branch (wip-mask-blending) to test another possible fallback -- minimum/maximum blend op instead of bitwise and/or. It requires SDL-side support for MIN / MAX rendering, which I implemented for OpenGL and OpenGL ES at https://github.com/libsdl-org/SDL/pull/7122

Also, @Wohlstand, commit https://github.com/Wohlstand/TheXTech/commit/c40f20444f962c922e08d3f7c56f97c7c4b7cf6b adds an API for the renderer to report its support for separate masks. This should make a clean API to optionally support your software render fallback too.

This is useful because OpenGL ES doesn't support true logic op rendering, and a lot of implementations don't include the pixel shader extension we'd need to simulate it. So this is our best chance to get even semi-accurate rendering at Android and Emscripten.

Here's a preview of how it works at the demo level from Light.zip:

<img  src="https://user-images.githubusercontent.com/72112344/213934594-630a205f-d4fb-4daa-b8a5-6218b76f800c.png" width="400" height="300"> <img src="https://user-images.githubusercontent.com/72112344/213934595-368adab5-328b-4715-80bd-1b44cf66f283.png" width="400" height="300">


It's not the same as vanilla but has similar attributes, like no overlap of multiple masks, and not affecting lower-valued backgrounds. What do people think about it?

**Comment by Wohlstand** [comment]
Looks very interesting. Also, feel free to apply the SDL update to the AudioCodecs side, and then it will be available by default on the rest of the platforms (that don't use system SDL2).

**Comment by 0lhi** [comment]
PR #539 is about to add a BETA OpenGL Renderer with Bitmask support to 1.3.6.1.

I'll change the Milestone for making OpenGL the default to 1.3.7.

**Comment by ds-sloth** [comment]
I don't think that anything is blocking making OpenGL the default, and it'll be valuable to have more users testing the OpenGL renderer family.

I made this change now for the main branch, and one of us can cherry pick it for the 1.3.6.x branch immediately after the 1.3.6.3 release.

**Comment by ds-sloth** [comment]
Completed in #539 and 624f6537b1c2548be54b44a13ddfae3cdbc9f9eb

For future reference - bitmask transparency is now displayed in a way fully compatible with SMBX 1.3 on the following clients:
- All OpenGL renderers (supported on Windows, Mac, Linux, Android, Switch, and Emscripten)
- Wii
- 3DS

It is displayed using the old conversion algorithm on the following clients:
- SDL2 (with a prominent warning at the top of the screen) (used on Wii U and PS Vita, may also be the preferred engine for some Windows users)
- Experimental minimal ports
