### ISSUE TITLE
[ Feature Request ] - Optional NSMB Bubble For Co-Op

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#266]
It would be nice if the Bubble System from NSMB were available as an option, as mentioned in #83 as it could make for both a more familiar experience, and a more useful one.

There are plenty of times in which a player re-spawning in normal gameplay is practically a death sentence or can sometimes clash with level design, but with the bubble system as an option, this problem can be mostly eliminated.

This could also be great if the "No Split" option mentioned in #46 were implemented, to recreate a feel that is mostly similar to NSMB's co-op.

I'd recommend making it a personal setting as to which is used, but also allow episodes and levels to override the setting in case the episode or level needs a particular style to work or in case the designer feels one is more fitting. For things like this, an 'allow episodes/levels to override settings' option may also be desirable... :thinking:

**Comment by ds-sloth** [comment]
> No Split

Well, the no split system will take a LOT of work to implement but I am interested in it also. It will allow us to have N-player multiplayer, which has been a feature we've been talking about for a long time. (I've tried to set up dynamic 4-player splitscreen and it is extremely difficult. If anyone has suggestions here I'd be interested to hear them.)

>For things like this, an 'allow episodes/levels to override settings' option may also be desirable.

I've been thinking for a while about allowing a hierarchy of settings (global, episode-level, and level-level user settings, and episode-level and level-level creator settings), where each level overrides the previous levels, and user settings always override creator settings. Internally, we'd probably also unify the config and compat systems under this feature, since there would not be any difference between the two any more.

Question: is there any case where we would want to have standard split-screen multiplayer, *AND* have bubbles? Want to understand how the features would overlap.

**Comment by 0lhi** [comment]
> Question: is there any case where we would want to have standard split-screen multiplayer, AND have bubbles? Want to understand how the features would overlap.

Good point. Imo, we should not do the Bubble thing. It seems appropriate for NSMB because it's made with local multiplayer on a single TV Screen in mind. For TheXTech though, this would just create an artificial limitation, which is always lame.

I think, the common wish here is to provide a quicker alternative for dropping / adding a Player via the Pause Menu. We should take time to find an approach that fits well with single-screen, split-screen and multi-screen, while taking other factors such as Netplay into account.

**Comment by ds-sloth** [comment]
> it's made with local multiplayer on a single TV Screen in mind

I think that the shared-screen use case is important (though less so during the pandemic :slightly_frowning_face: ), and we should implement Bubble for that purpose eventually. But I agree that Bubble doesn't make as much sense during split-screen multiplayer.

**Comment by 0lhi** [comment]
> I think that the shared-screen use case is important [...] and we should implement Bubble for that purpose eventually. But I agree that Bubble doesn't make as much sense during split-screen multiplayer

I'm not saying it's not important. I'm saying we should find one approach that works equally well for the shared screen as the bubbles, while also making sense for the other screen options.

That way we avoid the complexities that having different approaches for different screen options would entail.

**Comment by ChristianSilvermoon** [comment]
To be fair, I was specifically meaning that the feature should be a thing that is *optional* and something either enabled in settings and/or in an episode specific INI (as the original respawn mechanic can actually get in the way of some level design choice where the Bubble Mechanic would not).

So not replacing the original respawn, but rather adding an alternative option to it.

The idea behind No Split (as mentioned in #46) was to give players the ability to choose what happens in multiplayer when it comes to the screen: Dynamic Split (original behavior), Always Vertical or Horizontal (screen is always split and does not re-merge), and No Split (All players must remain on screen and the screen does not split)

The original respawning system also has a *major* issue with screen splitting, namely that the screen does not split until after respawning player is given control. This means that if Player 2 is respawning and Player 1 runs on ahead, the screen follows Player 1 and the respawning player is now offscreen, until it _very_ suddenly goes into dynamic split. In that time an obstacle capable of killing the freshly respawned player may now suddenly be in a position they didn't have time to react to because it occured off screen, leading to a sudden and very cheap death after respawning.

Several elements of the game lock up during respawns, which is clever and very helpful, but also doesn't universally apply to all NPCs, meaning certain level designs can still (although somewhat rarely by comparison) be broken by respawns.

With NSMB's Bubble Mechanic, the respawn does not have to interrupt any layer or NPC movement or leave the respawning player in a poor position, or respawn in a way that will compromise the still living player's gameplay. The respawning player can simply float harmlessly along, staying on screen, until the living player pops the bubble, returning them to play.

~~The screen not splitting for the respawning player should probably be it's own issue report tho, tbh~~

**Comment by ds-sloth** [comment]
As the priorities of TheXTech have changed, this idea no longer aligns with the main project aims of preserving the unique SMBX64 experience.

We are open to consider different means for improving player respawns, but those should be looked at in another issue/discussion.

**Comment by LoveBodhi** [comment]
It's unknown that this is doable via **Lua Script System** or not...
