### ISSUE TITLE
[Enhancement] Resolutions & Scaling

### ISSUE THREAD

**Issue by DanKruse731** [Wohlstand/TheXTech#312]
**Problem**
When playing in full-screen, the game does not scale properly to a 1920x1080 display. This results in pixels that are uneven, making the game look awkward. A lot of pixel-based games share this same issue, and is especially an ongoing trend in a lot of fan games (SM127, SM63Redux, etc.). There are multiple solutions to combating this issue, such as:

**Possible Solutions**
I would opt for reworking the game to support widescreen, but people just don't want to take the time to do that. Easier solutions include either integer scaling or filtering such as SMBX2b4 uses.

**Comment by ds-sloth** [comment]
I implemented this feature a while back and we're in the process of integrating it with the mainline engine. Check out #328. You can access a Windows build with the feature here: https://github.com/Wohlstand/TheXTech/actions/runs/2297038672. I'll close this issue but please feel free to share your comments in that thread.

Some notes regarding your particular question: integer, linear, and nearest-neighbor autoscaling are supported, and you can also manually specify 0.5x, 1x, and 2x scaling. A variety of resolutions are supported, but you're probably the most interested in 1280x720, dynamic-width 600p, and full dynamic resolution (up to 720p). 720p should scale well to your 1080p screen since most graphics are actually 2x upscaled already. Or you can set full dynamic resolution and ask for 2x scaling, it'll give you 2x 540p (shrinking the vertical playing field slightly).

<img src="https://user-images.githubusercontent.com/72112344/169674087-c65ed2f3-3ea8-4fd9-a196-365889e9dde9.gif" height="360">
