### ISSUE TITLE
Game Over screen

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#37]
Since everything, this game hadn't the proper game over screen, and there are next ideas:
- **Simple:** Show the "Game Over" on a black screen with the playing of the specific music, then, show the question to continue, or quit into the main menu.
- **More tricky:** In addition to simple, play some animation effects until the continue/quit question.
- **Like 38A does:** When a player has lost all lives, start the level specified as a "game over level" at the world map. When this level gets completed with any result, quit to the main menu.
- It's possible to don't show the question, just quit to the main menu, depending on settings.
- Optionally, add to the world map an option to disable the lives counter making them unlimited and useless (suggested for kaizo and other tricky or just hard episodes) (and let life shrooms act differently in this condition).

**Comment by MarioLover63** [comment]
Is it too much to ask for all three?

**Comment by Wohlstand** [comment]
> Is it too much to ask for all three?

It's possible to make work all of them depending on a world map settings and use the first one as the default for everything.

**Comment by ChristianSilvermoon** [comment]
I like the idea of all three

But I also like the idea of a generic "Game Over" level being used as a background for a Game Over Screen Menu thing, much like the Title and Credits Levels... maybe something like that could be overridden per world?

**Comment by 0lhi** [comment]
> Optionally, add to the world map an option to disable the lives counter making them unlimited and useless (suggested for kaizo and other tricky or just hard episodes) (and let life shrooms act differently in this condition).

Regarding the difficulty mode that we talked about, I looked at what other games are doing, and 4 approaches came to mind:

**Vanilla:** Start with 3 1UPs, get up to 99.

**Nuanced:** Start with 5 1UPs, get up to 999. (Same as SMA4, max resembles 38A, start resembles NSMB & All-Stars)

_**Dynamic:** 3 1UPs at the beginning, increase the amount after every game over, get up to 9999. (Resembles Sonic Robo Blast 2)_

**Casual:** Infinite Lives. (Resembles Odyssey, Crash 4 & Rayman Redemption)

In the case of Rayman Redemption's casual mode, the life counter is set to ∞. 1UPs turn into Tings (≈ Coins), and the Ting Counter doesn't stop at 99.

In Super Mario Odyssey, when a Player dies, he loses some of the Coins he collected.

You could combine these approaches to have something like this:

![Casual](https://i.imgur.com/olsh1i1.png)

Since Game Overs are impossible, I'd also suggest resetting the Point Counter after every death in Casual. Maybe for Dynamic, too, if you like the idea.

**Comment by Alucard648** [comment]
> > Optionally, add to the world map an option to disable the lives counter making them unlimited and useless (suggested for kaizo and other tricky or just hard episodes) (and let life shrooms act differently in this condition).
> 
> Regarding the difficulty mode that we talked about, I looked at what other games are doing, and 4 approaches came to mind:
Also: two more varieties:
Old School: Saving is disabled unless level was beaten via SMB3 ? sphere exit type, keyhole exit type,  SMB3 star
or via LUA script.
Hardcore: save will be automatically wiped out on getting Game Over.

**Comment by 0lhi** [comment]
> Old School: Saving is disabled unless level was beaten via SMB3 ? sphere exit type, keyhole exit type, SMB3 star,
or via LUA script.

Too situational I think. Some episodes would be hard, but Episodes with a hubworld wouldn't be affected at all.

> Hardcore: save will be automatically wiped out on getting Game Over.

If there is demand for that, it could be set to start with 1 and get up to 9. Would make a nice pattern.

**Comment by 0lhi** [comment]
Some additional ideas for the Infinite Lifes mode:

A death counter Instead of a Life Display:

![DeathCounter](https://user-images.githubusercontent.com/74732674/125961178-79fed338-9bc7-4045-ae9d-28f8d15e46bb.png)

Changing Scores 10-13 to getting 10/25/50/100 Coins:

![Scr_2021-07-16_16-08-38](https://user-images.githubusercontent.com/74732674/125961479-44f855a4-7d32-402e-b44f-7ba0199382e6.gif)

For Worlds with "*Restart last level after death*" enabled:

A Quick death that skips the death animation and keeps the soundtrack playing:

![2021-07-16_16_14_48](https://user-images.githubusercontent.com/74732674/125961800-c745085b-829a-4274-8fd3-72dab9f23ed4.gif)

Inspired by [A Tiny World Episode](https://www.supermariobrosx.org/forums/viewtopic.php?f=36&t=27087) by MrDoubleA.

**Comment by Wohlstand** [comment]
**A small note:** since the new lifes system will be developed, the Game Over screen would not be needed in the future.

**Comment by ChristianSilvermoon** [comment]
> **A small note:** since the new lifes system will be developed, the Game Over screen would not be needed in the future.

New Lives system? Will there no longer be a possibility to lose all lives?

**Comment by ds-sloth** [comment]
Yes, that's correct! In non-compatibility modes, the Lives counter has been replaced with a "Balance" counter of how many 100s of coins / 1UPs the player has collected. This Balance counter is allowed to go negative, but (like what happens with a Game Over in SMBX 1.3), the Score is set to zero whenever a player loses a life when their Balance is zero or negative.

**Comment by LoveBodhi** [comment]
That means, infinite lives in modern gameplay mode!

**Comment by ds-sloth** [comment]
Basically, yes, if the player does not care about their run's score.
