### ISSUE TITLE
[BUG] Checkpoint doesn't work when using world map

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#373]
**Describe the issue**

In the latest development build, checkpoint doesn't work when using world map, but works fine if not use world map.

**Example Case**

[002.zip](https://github.com/Wohlstand/TheXTech/files/9276299/002.zip) (Requires Nostalgic Paradise asset!)
[TheXTech_log_2022_08_07_14_33_27.txt](https://github.com/Wohlstand/TheXTech/files/9276300/TheXTech_log_2022_08_07_14_33_27.txt)

**Recording**

![Scr_2022-08-07_14-33-40](https://user-images.githubusercontent.com/37089530/183278450-a8a58a73-2d23-4232-9834-e9f614525761.gif)

**Vanilla Recording**

None

**Additional context**

None

**Comment by Wohlstand** [comment]
Confirmed just now, even on normal assets, this is a bug of engine itself:
![Scr_2022-08-07_19-37-07](https://user-images.githubusercontent.com/6751442/183301561-d3518dad-8188-4b70-b37e-ba3afcf9353a.gif)

**Comment by Wohlstand** [comment]
I also confirm, they works normally on 1.3.5.3 version.

**Comment by 0lhi** [comment]
Could this be related to #371 and #152 ?

**Comment by ds-sloth** [comment]
I'd strongly suspect it's related to #371. There was an issue where some of the FileName variables weren't being restored to the world's variables when returning to the world. But, I'd guess that the checkpoints system relied on not restoring those variables. We could either (1) save the most recently visited *level* separately so that clearing checkpoints works (this makes the game's internals cleaner, but adds ~80 more bytes of RAM -- this is practically nothing on our target platforms), or (2) revert the fix for #371 and make another fix that more narrowly targets the issue, saving this RAM but making the internal code more convoluted.

**Comment by Alucard648** [comment]
I prefer 1). 80 bytes of RAM is not that meaningful on modern platforms.

**Comment by ds-sloth** [comment]
As I suspected, it's this incorrect line here: https://github.com/Wohlstand/TheXTech/blob/f913d6b0/src/player.cpp#L108

I'm going to fix it by adding a check to not clear checkpoints if `LevelSelect` is set.

Sorry for not catching this when fixing #371.

**Comment by ds-sloth** [comment]
@LoveBodhi can you check whether the issue still occurs?

**Comment by LoveBodhi** [comment]
Problem fixed❤

**Comment by Wohlstand** [comment]
I also confirm the bug has gone! :)

![Uploading Scr_2022-08-08_01-50-43.gif…]()

**Comment by Wohlstand** [comment]
P.S. Please remove the "NEED A TEST" label from cases that were tested and confirmed as solved.
