### ISSUE TITLE
Worldmap: Viewport Areas from 38A for Multires

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#397]
The 38A-Worldmap features Areas that can be set to work as Viewpoints, which confine the Movement of the Camera to the Area as long as Player is inside it:

![output](https://user-images.githubusercontent.com/74732674/186510633-beba8c93-6946-4a98-9468-767982f59385.gif)

![Viewports](https://user-images.githubusercontent.com/74732674/186516329-a1b6cc2a-e524-4efc-ae91-de10e1ffcd3c.png)

This is incredibly useful for Multires to ensure the Camera doesn't show any empty spaces.

The Areas could be integrated nicely into the Moondust Editor by attaching them to the currently unused Section Numbers:

![MoondustSections](https://user-images.githubusercontent.com/74732674/186513904-75817bf7-8476-4c20-9d02-2e0a5b235b94.png)

The Areas are defined by this Part of the .wld file:

```
M|0|320|64|||1056|800|7|,0
M|1|-256|0|||896|800|3|,0
```

[AMAP.wld.zip](https://github.com/Wohlstand/TheXTech/files/9419710/AMAP.wld.zip)

**Comment by ds-sloth** [comment]
* How many areas would be supported, maximum? 20? 100? 255?
* If a user accidentally activates an uninitialized area, should that just not restrict the viewport at all?
* Would we use World Music-like objects to set the current area?
* Should we try to support importing actual 38A content to this system? If so, what would that require?

I can totally write a qScreen system to pan and possibly resize the viewport whenever Mario changes area (except at a warp, where there is already a fade).

**Comment by Wohlstand** [comment]
Note that on the world map the QScreen-like system shouldn't pause the gameplay, and also, it can be used for a smoother path opener process (like I made at Moondust Engine, and how 38A was made later)

**Comment by ds-sloth** [comment]
I also propose that, since this is a major rewrite, we might pair it with the implementation of multiple world players? I have always thought this was one of the biggest defects of SMBX multiplayer.

**Comment by ChristianSilvermoon** [comment]
> I also propose that, since this is a major rewrite, we might pair it with the implementation of multiple world players? I have always thought this was one of the biggest defects of SMBX multiplayer.
> 
> Edit: obviously if people like this idea, it belongs in another issue. :)

Would this imply different players could visit different levels at the same time? :O

**Comment by ds-sloth** [comment]
That's going a bit far even for me! But we could possibly set up splitscreen for the world map. (That's what made me think of implementing the feature in the first place.)

**Comment by ChristianSilvermoon** [comment]
> That's going a bit far even for me! But we could possibly set up splitscreen for the world map. (That's what made me think of implementing the feature in the first place.)

I just can't imagine what else you'd do with a split screen world map x3

**Comment by ds-sloth** [comment]
Mainly just making it fair which player selects the level! As it is, it feels a bit unfair to P2 that P1 always gets to make the selection.

**Comment by ChristianSilvermoon** [comment]
> Mainly just making it fair which player selects the level! As it is, it feels a bit unfair to P2 that P1 always gets to make the selection.

I'd suggest a system to pass off control maybe, then :thinking:

**Comment by ds-sloth** [comment]
I'll try to develop this for 1.3.7. It'll nicely resolve the design issues @0lhi identified with freely expanding the viewport of the world map.

I've put an initial mockup in the multires branch. It can be previewed by opening a 38A world including world map areas.

@Wohlstand, the implementation is quite simple:
* `WorldMusic_t` items may now have a non-30x30 size.
* If their size is greater than 64x64, then a static variable `currentSection` can be set in `world_loop.cpp`. The current section is chosen to contain the largest possible area centered on the player. In case of a tie, the smaller section overall is chosen. (This can be used to hide junk at L junctions.) The physical screen size is not considered.
* `world_loop.cpp` updates the vScreen offset and on screen position. It constrains the `vScreen` size based on the viewport, or otherwise the compatibility mode. It also supports a `qScreen`-like system as we discussed before.

I've done my testing at a custom view of 2560x1440 (qHD) and at HD view.

I'd welcome all of your feedback on the feature's user-facing design. Is the animation good? What could be changed to make it more "natural" and user-friendly?

**Comment by Wohlstand** [comment]
I vote to have an unique object type for such things, just to not confuse music boxes and special areas, BUT, if think that these areas also may change the music by entering to them, they could also have such functionality.

**Comment by ds-sloth** [comment]
I'm fine with that, that would also allow us to limit the number of special areas, and give them more of the powerful features from 38A areas in the future.

But right now, I'm not sure if the actual design is good, so I'd like to get more feedback on that first. The previous attempts (world map fog and automatic resizing) didn't work that well, and I'd like to make something that is polished for users and easy for creators and repackers to use.

**Comment by ds-sloth** [comment]
> Note that on the world map the QScreen-like system shouldn't pause the gameplay, and also, it can be used for a smoother path opener process (like I made at Moondust Engine, and how 38A was made later)

I added a smoother path opening animation to the most recent multires builds; once people like it I can backport it to main.
