### ISSUE TITLE
Fancy Character Selection for Multiplayer

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#402]
One subject discussed in the Abstract Controls Pull Request that was kept for later is the idea of a fancier Multiplayer Screen:

![Multiplayer](https://user-images.githubusercontent.com/74732674/187184565-2c8c95a0-a077-46c1-87de-1e65bff0f177.png)

> @0lhi The Power-Up status of the Character should be indicated. The selected Characters should play the running animation.

> @ds-sloth (1) The screen is ugly: yes. I picked it this way to make it as similar to the experience of the original game as possible but allowing the two players to select their characters at the same time. Your design looks fantastic. I can try to make something like it. Do you think it should be used by default? Always or just for multiplayer? There are also some uncertainties in your proposal. What should happen when player 1 is selecting a character and player 2 is selecting a profile?

> @0lhi
>> (1) Do you think it should be used by default?
>
>Yes!
>
>> Always or just for multiplayer?
>
>Just for Multiplayer. Singleplayer game should presume that the the controls are already setup to the Players liking, and stick with the Classic Character Selection. This is actually important for Mode 2 & 3, since Menu Quits are allowed in Speedruns.
>
>> There are also some uncertainties in your proposal. What should happen when player 1 is selecting a character and player 2 is selecting a profile?
>
>Move the Profile and Testing Controls Menu a bit down, and lock Player's 2 Cursor inside it, while Player 1 can still navigate freely.

**Comment by ChristianSilvermoon** [comment]
I actually would prefer to see the new character selection for single player too, both for the sake of consistency **and** seeing the power up state ahead of time.

It's not uncommon that I'll use different characters to 'store' power-ups in a run, so seeing it ahead of time could save me switching later. I'd strongly prefer it.

**Comment by 0lhi** [comment]
Counterpoints:

1. A strong visual distinctions will make Players immediately clear when they're in the wrong Screen (a problem that I've been having)
2. It would be a too big deviation from other SMBX Versions
3. It might invalidate Mode 2+3 Runs as it'd give Players an information advantage.

The Single Player Selection shouldn't be touched.

I wouldn't mind making a 1P Game accessible from the Multiplayer Screen, however.

**Comment by ChristianSilvermoon** [comment]
> A strong visual distinction will make Players immediately clear when they're in the wrong Screen (a problem that I've been having)

This sounds more like a separate readability issue :P

> It would be a too big deviation from other SMBX Versions

It's purely cosmetic and helpful, while it might be different, I don't see how different is inherently wrong. 

> It might invalidate Mode 2+3 Runs as it'd give Players an information advantage.

Since the major concern of Speed Runs is to keep things accurate to original, the old look should be used for speed runs.

> I wouldn't mind making a 1P Game accessible from the Multiplayer Screen, however.

Now that you mention it, I wouldn't mind seeing the entire concept of "1 Player Game" and "2 Player Game" eliminated and replaced with "Play Episode" and have the players determined dynamically at character selection... in fact, I'd prefer it, *but* only if the old menu is retained for speedrun modes.

**Comment by ChristianSilvermoon** [comment]
> A strong visual distinction will make Players immediately clear when they're in the wrong Screen (a problem that I've been having)

This sounds more like a separate readability issue that should be fixed in some other manner :P

> It would be a too big deviation from other SMBX Versions

It's purely cosmetic and helpful, while it might be different, I don't see how different is inherently wrong. 

> It might invalidate Mode 2+3 Runs as it'd give Players an information advantage.

Since the major concern of Speed Runs is to keep things accurate to original, the old look should be used for speed runs.

> I wouldn't mind making a 1P Game accessible from the Multiplayer Screen, however.

Now that you mention it, I wouldn't mind seeing the entire concept of "1 Player Game" and "2 Player Game" eliminated and replaced with "Play Episode" and have the players determined dynamically at character selection... in fact, I'd prefer it, *but* only if the old menu is retained for speedrun modes.

**Comment by 0lhi** [comment]
> This sounds more like a separate readability issue that should be fixed in some other manner :P

This was the sole reason for my suggestion. Which I'd rather do without entirely than have it affect the 1P Screen.

> It's purely cosmetic and helpful, while it might be different, I don't see how different is inherently wrong.

Different is contextually wrong when it breaks a previously established pattern in a project whose primary concern is preservation.

New Stuff is welcome as long as it does not get in the way of how one would expect SMBX64 to work.

> Since the major concern of Speed Runs is to keep things accurate to original, the old look should be used for speed runs.

Accuracy is a major concern of speedruns, but not exclusive to speedruns. It's also not worth to add an inconsistency between Casual Menu and Speedrun Menu for not much benefit.

> I wouldn't mind seeing the entire concept of "1 Player Game" and "2 Player Game" eliminated and replaced with "Play Episode" and have the players determined dynamically at character selection... in fact, I'd prefer it

So I'm against elimination, but I've been for renaming them to "Singeplayer" and "Multiplayer" for a while. Multiplayer is a loose term that would leave the option for 3P and 4P open in the future. Since the amount of Players is undefined, we could easily allow to start a 1P Game here as well. That would allow you to check Power-Ups without making sacrifices anywhere else.

**Comment by LoveBodhi** [comment]
Typo was found: Singeplayer → **Singleplayer**

**Comment by ds-sloth** [comment]
You might remember that in early drafts of the Abstract Controls update, there was only a “Start Game” menu option with no player distinction. I’d be very happy to do this again, if we can figure it a way to make it easy to use the original behavior during menu quits from a speed run and easy to restore the original behavior in settings.

Also note that our “quick select last episode” feature already invalidates menu quits to a certain extent.

**Comment by 0lhi** [comment]
> Also note that our “quick select last episode” feature already invalidates menu quits to a certain extent.

Nope. Menu Quits are not being timed on branches using IGT (X2 & XTech). So merely highlighting the last played Episode is fair game. The effect is the same as putting a single episode in the *world* folder.

**Comment by SavaRaine** [comment]
Here is my idea for the character select menu. I have 8 players here but you could subtract boxes to decrease the amount. The 2nd screenshot shows if all players pressed the A button which leads player 1, 5, 6, 7 and 8 to have their character ready and leads player 2 into the controller testing, player 3 to the control options and player 4 to be disconnected. Any text that is long should probably scroll but for a lot of things icons should be better since they take up a lot less space than text and can look neater. :>
![Character Select Idea](https://user-images.githubusercontent.com/16658822/212541866-cb9559bc-3694-426c-9e28-7d8f42417a02.png)

**Comment by LoveBodhi** [comment]
This makes me think about NSMBWii.

**Comment by ds-sloth** [comment]
I'm posting this image from @Savbyn so that I can remember our current design discussion. The boxes would probably be connected. The player name would always be shown; the bottom text would either be the controller profile name or the description for the currently selected action icon.

![image](https://github.com/Wohlstand/TheXTech/assets/72112344/b880e78a-5091-4779-93ad-ccd535c0a1f4)

**Comment by ds-sloth** [comment]
I renamed the issue since the previous title only makes sense for historical reasons.
