### ISSUE TITLE
Incorrect global block size for the new in-game editor

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#423]
![Scr_2022-09-28_08-06-11](https://user-images.githubusercontent.com/37089530/192660021-f9e32792-839e-4be6-a2ba-fa603ca065e5.png)

Tested with Third Returns: https://github.com/LoveBodhi/third-returns (Incomplete)

**Comment by ds-sloth** [comment]
I've looked closely at the implementation here, and it turns out that SMBX64 and TheXTech do not truly support custom block sizes, and certain cases like block shaking and P-Switches can raise unexpected issues when blocks are not their original width.

I wouldn't recommend implementing this feature, until TheXTech natively supports custom block sizes. So maybe not in 1.3.6.1, but soon.

@0lhi This may be related to #167 . What do you think?

**Comment by LoveBodhi** [comment]
> TheXTech natively supports custom block sizes

Actually supports, and it can be placed by Moondust directly.

**Comment by LoveBodhi** [comment]
Therefore, issue is closed due to it's hacked blocks.
