### ISSUE TITLE
[Optional Setting] New player running mechanic

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#426]
When player hold "run" and the direction pad on the ground for an amount of duration, player speeds up. This sorts like original SMB3 and SMW.

> Inspired from Gatete Mario Engine

**Comment by ds-sloth** [comment]
Thanks for the suggestion! This is already a feature internally, though the time to peak speed is relatively lower in SMBX than many related games.

Since our project targets SMBX logic, this is a more appropriate goal for a more general engine. But you may be able to get a similar effect by tweaking the player physics values. If there isn't already, there will be a way to do this once we implement scripting.

**Comment by ChristianSilvermoon** [comment]
I think this should be handled as a part of physics customization :P
whether through scripting or episode-side configs

**Comment by LoveBodhi** [comment]
> I think this should be handled as a part of physics customization :P whether through scripting or episode-side configs

Right, this is ACTUALLY player physic related setting.

**Comment by LoveBodhi** [comment]
> Since our project targets SMBX logic

We should have "Mode Switch" Setting via gameinfo.ini, Mode 0 is Classic (Original SMBX Mode), and Mode 1 is modern mode (Non-SMBX). This affects my Open Source Asset, New Fairy Tale Wonderland.

**Comment by 0lhi** [comment]
A new discussion for possible physics changes has been opened to keep things coordinated:

https://github.com/Wohlstand/TheXTech/discussions/636

Feel free to bring up your idea there!
