### ISSUE TITLE
Broken Unhidable Battery Indicator on Switch

### ISSUE THREAD

**Issue by poudink** [Wohlstand/TheXTech#444]
**Describe the issue**

A battery indicator is present on the lower left corner of the screen. This battery indicator cannot be hidden, even if configuration files are explicitly set to have it hidden. It also fails to actually display the battery level, instead indicating that the battery level is unknown. The indicator seems to be for the controllers rather than the Switch itself, since one more appears when playing with another player. Worth noting that playing in single player will always display only a single battery indicator even if playing with two controllers (such as a pair of joycons).

**Example Case**

N/A (happens in every episode or level)

**Vanilla Recording**

N/A (battery indicators weren't in vanilla)

**Additional context**

This is really the only issue I've had with the (seemingly new) Switch port so far and I'm pretty impressed with it overall. With this fixed I'd consider it to be fully usable.

Screenshot TBA.

**Comment by ds-sloth** [comment]
Thanks for the report and for your interest in our Switch port!

It would be an SDL defect that the controller battery indicator is not working. I don’t remember whether we currently have any  patches in our SDL build; if so it might be possible to fix that pretty easily. Otherwise we’d probably want to replace the SDL game pad bindings with direct Switch API bindings (as we do in our 3DS and Wii ports). I also wonder whether SDL reports the system power status properly.

I’m a bit surprised the controller battery status was on by default. Can you confirm whether you had the input display (show which buttons are pressed) enabled? Additionally, can you confirm whether this happens when you configure the controller profile to not  display battery status?

**Comment by Wohlstand** [comment]
> It would be an SDL defect that the controller battery indicator is not working.

Ye, on some platforms controller battery indicator, is inaccessible: on Android, it basically lacks the necessary API for that, except for HIDAPI-based controllers where their state gets received directly.

**Comment by ds-sloth** [comment]
I think the best solution here should be to change the default setting for new controller profiles to disable this until the user enables it in the controller profile settings.
This isn't an essential piece of information, but it's annoying to have a broken indicator, so I think it is fine to disable it by default.
