### ISSUE TITLE
Vanilla Levels that require a specific compat.ini Fix to work

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#54]
We already have a few examples for levels that require a [Compatibility Feature](https://github.com/Wohlstand/TheXTech/wiki/compat.ini---Tune-the-compatibility) to work properly. Wohlstand may add a feature that automatically applies specific fixes to levels with certain hash values (can be displayed by [Gtkhash](https://github.com/tristanheaven/gtkhash/releases)). ~~This issue is meant to keep track of those levels.~~

**EDIT: A new Repo has been made for Vanilla Issues -  Please report them here: [Wohlstand/TheXTech-VanillaFixes](https://github.com/Wohlstand/TheXTech-VanillaFixes)**

**EDIT 2: Closing this as the Idea of a Patch System has officially been abandoned. See #355.**

**Comment by Wohlstand** [comment]
Just now I found that `Docopoper-Life_Lift.lvl` at Prelude To The Stupid needs the next flag:
```ini
[compatibility]
fix-npc-downward-clip = false
```
Otherwise, lift will destroy some walls and confuse enemies on the path

**Comment by ChristianSilvermoon** [comment]
I'm imaging a list of levels like this being maintained via git so that anyone can contribute compatibility info

The game could then fetch from somewhere like below upon player request:
`https://raw.githubusercontent.com/some-user/thextech-level-compatabillity-db/master/compatabillity.txt`

The game would/could ship with whatever the latest on the master branch is at the time of building.

The master branch cold be treated as a 'approved' branch for additions that are verified to be needed / are correct.

But in the menu there could be options to:
• Select URL for the compatibility list (So that it's not stuck to one source and anyone can host their own)
• Update local compatibility data from URL

If there are flags the game doesn't support, the best choice would be to ignore them, so that the compatibility database is treated as version agnostic.

**Comment by LoveBodhi** [comment]
Needs to set compatibility level for vanilla SMBX 1.3 asset.
