### ISSUE TITLE
Purle Yoshi can bypass instant warps by performing the Ground Pound

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#544]
**Describe the issue**
The problem originally reported by `Radianc (@radianceeeeeeee)` at Discord.

> Ground pounding with Purple Yoshi leads to death rather than warping

![Screenshot_2023-06-21-19-49-54-87_fc9b0eb1832cb4f1879c12bf3b54568e](https://github.com/Wohlstand/TheXTech/assets/6751442/923afc18-9189-4a5f-bde9-4f422c940572)

When Purle Yoshi performs a Ground Pound, it can bypass any instant warps by performing the Ground Pound.

**Example Case**
The simple demo level. Clouds are points of the instant warp. If fall into the instant warp normally, the warp will just work. When fall with performing the Ground Pound, therefore warp point will be bypassed.

[purleYoshi.lvl.zip](https://github.com/Wohlstand/TheXTech/files/11817364/purleYoshi.lvl.zip)

**Vanilla Recording**
![Scr_2023-06-21_15-08-48](https://github.com/Wohlstand/TheXTech/assets/6751442/17bcbc77-4639-46ff-9a31-624995df28b5)

**Comment by SkullGamer205** [comment]
@Wohlstand , this bug also works with PORTAL warps?

**Comment by Wohlstand** [comment]
> @Wohlstand , this bug also works with PORTAL warps?

Very likely, because it's a problem of a general collisions code I guess, however, I'll need to check why it misses up these warps: or it intentionally skips them, or they just gets skipped because of too fast motion :thinking:

**Comment by ds-sloth** [comment]
I think that we discussed this on Discord and that it is intentionally skipped. (Check source code of `SuperWarp`.)

With a compat flag check, it should be pretty easy to fix this -- move the GroundPound check into the loop and only apply it for standard / door warps. I wouldn't object if you want to do it directly in the `main` branch and we review here.

Since this can cause unfair player deaths, I suggest we should try to fix it in the 1.3.6.1 release.

**Comment by ds-sloth** [comment]
Should be fixed in the main branch now. Added a compat flag `fix-pound-skip-warp`, which determines whether Instant and Portal warps are checked when the player is performing the Pound move. I'll ask Radiance to confirm in Discord.

<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/398c6b4d-837e-481e-a416-65186841db4b" width="400" height="300"> <img src="https://github.com/Wohlstand/TheXTech/assets/72112344/af1f400b-1339-47df-8076-91fef3804be6" width="400" height="300">

**Comment by ds-sloth** [comment]
Fix confirmed by Radiance.

@Wohlstand, feel free to close this issue following your review and confirmation that the fix looks good.

**Comment by Wohlstand** [comment]
From my side, I confirm the fix just works:
![Scr_2023-07-30_00-15-40](https://github.com/Wohlstand/TheXTech/assets/6751442/d3273cfa-78d3-46da-9578-69c4144495c3)

**Comment by Wohlstand** [comment]
I'll close this. And the last thing is a waiting when Radianc will confirm the fix on his side.
