### ISSUE TITLE
TTF Font issue on "Pause Menu" with OpenGL Renderer

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#590]
![Scr_2023-08-21_15-08-24](https://github.com/Wohlstand/TheXTech/assets/37089530/75996320-c025-4d88-8cec-a41f1d9bd939)

OpenGL

![Scr_2023-08-21_15-09-59](https://github.com/Wohlstand/TheXTech/assets/37089530/045c063c-96da-4932-96f1-d0b17c797046)

HW (SDL2)

**Comment by ds-sloth** [comment]
Excellent bug, thanks very much for reporting this. Can you please confirm that it is fixed now?

@Wohlstand, you should note this also: the problem occurred because I wasn't properly validating externally loaded (TTF) textures for the depth test. I fixed this by adding validation code to the public `AbstractRender_t::loadTexture` method.

**Comment by LoveBodhi** [comment]
![Scr_2023-08-22_05-59-33](https://github.com/Wohlstand/TheXTech/assets/37089530/7cc7187d-3ecc-460d-9354-03d2f06eed79)
Works now
