### ISSUE TITLE
Feature Request: Add/Drop Player 2 In Game

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#83]
Just the ability to have player 2 join an already existing game.

Could have a character selection menu pop up if Player 2's controller presses Start while the game is paused on World Map or in Hub. Could also Drop Player 2 by repeating the action?

**Comment by Wohlstand** [comment]
That also needs to have the case when the episode is able to play two-player game (for example, episode where is only one character unlocked, can't be played in two-player mode properly, you'll just get two clones of the same character)

**Comment by 0lhi** [comment]
As I have recently noticed, the 1player and 2player codes can pretty much do this. Until a non-code solution is added, should we just comment out the "_cheated = true;_" lines from cheat_code.cpp? It does the job on the build I just made:

![Scr_2021-06-10_23-33-05](https://user-images.githubusercontent.com/74732674/121600650-0fb4e680-ca45-11eb-9cac-4e95c6b54592.gif)

Player 2 pressing Start does not pause the game (but it does activate the captainn Cheat). So, a good solution I think would be to have his Start button trigger *2Player* to add, and *1Player* to drop. Wouldn't allow to immediately choose the character, but, I think that's better since it doesn't break the flow of P1. At least for World Map episodes. Hubworlds should also allow to change characters, but that's a seperate issue.

Also: Typing 2Player during 2P Mode leads to this:

![Scr_2021-06-10_23-35-43](https://user-images.githubusercontent.com/74732674/121602153-2eb47800-ca47-11eb-807c-3f8d87a5720e.gif)

This seems totally pointless to me. If the Start Trigger is added, I think this should be commented out, too.

**Comment by ChristianSilvermoon** [comment]
That functionality does seem to work well as a start, but I think it should only work in Hub World areas and on the World Map.

Switching to 2P mode mid level should probably stay a cheat

**Comment by 0lhi** [comment]
> but I think it should only work in Hub World areas and on the World Map.

Disagree with that. The Lego Games allow to enter/leave Co-Op at will, which makes for a great experience that offers much flexibility.

It would be useful to know how NSMB and 3D World handle it. I know they do have multiplayer, and I know that in NSMB they can respawn after dying (the bubble thing), but that's about it.

**Comment by 0lhi** [comment]
The Game does not remember which Player was used last. Have no opinion on this yet.

![Scr_2021-06-11_00-54-50](https://user-images.githubusercontent.com/74732674/121607084-b69e8000-ca4f-11eb-83b3-99ee2c047515.gif)

**Comment by ds-sloth** [comment]
This is a feature that will be added in the `wip-abstract-controls` update.

I agree with @0lhi that we should allow drop/add at any time, preferably from the pause menu. Additionally, to deter cheating, we should only make the first time the second player is added "free", and additionally times will cost one life each. (If the second player's controller drops, the game will automatically pause to allow them to rejoin for free.) Does that seem like a good approach to both of you?

**Comment by 0lhi** [comment]
No, that wouldn't be good. It would cause players to lose lives on obstacles that don't take multiplayer into account, for no fault of their own.

![Scr_2021-07-09_15-17-03](https://user-images.githubusercontent.com/74732674/125083506-c77ef780-e0c8-11eb-98a9-42073ef6e27f.gif)


It's not unusual for Co-Op platformers at all to allow one Player to skip a tough section. *Bugs & Taz - Timer Busters* enables teleportation to the other player, *Crash of the Titans* allows to carry the partner in a backback, and NSMBWii has the Bubbles, that, as I found out yesterday, can be activated at any time.

There is no reason not to allow it in SMBX as well. People who feel like it's cheating may just not use it. But this is a subjective view that should not be imposed on all players.

**Comment by Wohlstand** [comment]
SMBX allows to carry buddy if you have Yoshi and you can carry your buddy in his moth, then spit when needed

**Comment by Wohlstand** [comment]
![Scr_2021-07-09_16-36-10](https://user-images.githubusercontent.com/6751442/125085990-d6b77280-e0d3-11eb-9c06-0fa32bbe9978.gif)

**Comment by 0lhi** [comment]
Interesting! I had no idea :o

This offers quite some cheese potential 🤔

![Scr_2021-07-09_15-39-52](https://user-images.githubusercontent.com/74732674/125086459-f3e84300-e0cb-11eb-89ae-86f865cb81e6.gif)

But it's not a universal solution.

**Comment by ds-sloth** [comment]
> There is no reason not to allow it in SMBX as well. People who feel like it's cheating may just not use it. But this is a subjective view that should not be imposed on all players.
That is true, especially given that we probably should not add full drop/add functionality in compatibility mode (perhaps we can allow drops at least when a controller is disconnected?). At the same time, for casual players, it might be unintuitive to use the drop/add functionality for this purpose, so we might eventually want to implementing bubbles for such players.

**Comment by 0lhi** [comment]
> That is true, especially given that we probably should not add full drop/add functionality in compatibility mode

Exactly.

> (perhaps we can allow drops at least when a controller is disconnected?)

That would disqualify Speedruns where it happens on accident, so, better not.

> At the same time, for casual players, it might be unintuitive to use the drop/add functionality for this purpose

I think it can be made intuitive. "Add" could be done by the inactive Player pressing Start, and that could be indicated at the top right/left corner. "Drop" would be done through the Pause Menu. (Similar to how it's done in Lego games).

![P2-Add](https://user-images.githubusercontent.com/74732674/125126431-63c1f200-e0fb-11eb-8ee2-c6f1fbecf774.png)

> so we might eventually want to implementing bubbles for such players.

If going for that direction, a relatively uncomplicated approach would be to give Players the ability to turn into a Boo, which will follow the remaining Player until a trigger occurs (contact or button press).

![Scr_2021-07-09_21-17-26](https://user-images.githubusercontent.com/74732674/125126415-5d337a80-e0fb-11eb-98e0-8e752fbe7f60.gif)

**Comment by ChristianSilvermoon** [comment]
We could totally reuse the Super Mario World Bubble graphic in conjunction with the player death effect sprites

**Comment by ds-sloth** [comment]
I was hoping to do that also, @ChristianSilvermoon ! I think that something with the SMW Bubble graphic and boo-like logic could work very well.

But first things first, the drop/add. We can certainly (and easily) add a drop/add screen to the pause menu. However, because of the way that controllers work are implemented, polling for new controllers *every frame* could be a little expensive if the poll methods are not well-optimized. How much of an advantage (user-wise) is polling every frame?

**Comment by 0lhi** [comment]
> We could totally reuse the Super Mario World Bubble graphic in conjunction with the player death effect sprites

I could see this work.

![Scr_2021-07-10_11-35-35](https://user-images.githubusercontent.com/74732674/125158722-344ecc00-e173-11eb-9157-c36dcdb174f7.gif)

A minor disadvantage however is that it'd imply a small player state. Unless we'd make dedicated sprites for every state? Link would need a new default state sprite since effect-134 is too big for the bubble.

**Comment by ChristianSilvermoon** [comment]
I kinda feel the bubble should behave more akin to the way it does in the NSMB games, but I don't particularly have any objections to this other than that :P

**Comment by 0lhi** [comment]
The Drop/Add was added with #245, so this should be good to close.

The Bubble Feature can be discussed in a new thread, if need be.
